# Generated by Django 5.2.5 on 2025-08-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyresult',
            table='facturas',
        ),
    ]
